version: '3.8'
services:
  cloudflared:
    build: 
      context: ./cloudflared
      dockerfile: Dockerfile-2020.5.1
    image: cloudflared:2020.5.1
    networks:
      dns_network:
        ipv4_address: 172.18.0.2
    environment:
      - TZ=Asia/Bangkok
      - TUNNEL_DNS_ADDRESS=0.0.0.0
      - TUNNEL_DNS_PORT=53
      - TUNNEL_METRICS=0.0.0.0:10080
      - TUNNEL_DNS_UPSTREAM=https://security.cloudflare-dns.com/dns-query,https://security.cloudflare-dns.com/dns-query
      - TUNNEL_DNS_BOOTSTRAP=https://1.1.1.1/dns-query,https://1.0.0.2/dns-query
    restart: always
    dns:
      - 1.1.1.1
      - 1.0.0.1
    healthcheck:
      test: ["CMD-SHELL", "dig +norecurse +retry=0 @127.0.0.1 cloudflare.com google.com || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 2
      start_period: 1s 

  pihole:
    image: pihole/pihole:v5.0
    ports:
      - 53:53/udp
      - 53:53/tcp
      - 80:80
    networks:
      dns_network:
        ipv4_address: 172.18.0.3
    volumes:
      - /opt/dns/pihole/etc-pihole:/etc/pihole
      - /opt/dns/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=Asia/Bangkok
      - DNS1=172.18.0.2
      - DNS2=172.18.0.2
    restart: always
    dns:
      - 127.0.0.1
      - 172.18.0.2
    depends_on:
      - cloudflared

networks:
  dns_network:
    name: dns_network
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
